version: "3.9"

services:

  nextjs1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    # volumesを完全に削除
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=ws://ws-server:8080
      - VOICEVOX_ENGINE_URL=http://voicevox_engine:50021
    depends_on:
      - ws-server

  nextjs2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    # volumesを完全に削除
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=ws://ws-server:8080
      - VOICEVOX_ENGINE_URL=http://voicevox_engine:50021
    depends_on:
      - ws-server

  ws-server:
    image: node:16.14.2
    working_dir: /app
    volumes:
      - .:/app
    command: node server/ws-server.js
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - WS_PORT=8080
      - WS_HOST=0.0.0.0

  voicevox_engine:
    image: voicevox/voicevox_engine:nvidia-latest
    ports:
      - '50021:50021'
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50021/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nextjs1_node_modules:
  nextjs1_next:
  nextjs2_node_modules:
  nextjs2_next:
