version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=ws://ws-server:8080
      - VOICEVOX_ENGINE_URL=${VOICEVOX_ENGINE_URL}
    depends_on:
      - ws-server

  ws-server:
    image: node:16.14.2

    working_dir: /app
    volumes:
      - .:/app
    command: node server/ws-server.js
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - WS_PORT=8080
      - WS_HOST=0.0.0.0
