# version: "3.9"

services:

  nextjs1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    # volumesを完全に削除
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=ws://ws-server:8080
      - VOICEVOX_ENGINE_URL=${VOICEVOX_ENGINE_URL}
    depends_on:
      - ws-server
    # env_file:
    #   - ./.env

  nextjs2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    # volumesを完全に削除
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=ws://ws-server:8080
      - VOICEVOX_ENGINE_URL=${VOICEVOX_ENGINE_URL}
    depends_on:
      - ws-server
    # env_file:
    #   - ./.env
      
  ws-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - WS_PORT=8080
      - WS_HOST=0.0.0.0


volumes:
  nextjs1_node_modules:
  nextjs1_next:
  nextjs2_node_modules:
  nextjs2_next:
