version: "3.9"

services:
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-amd64-latest
    ports:
      - "50021:50021"
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50021/docs"]
      interval: 30s
      timeout: 10s
      retries: 3